// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gyjviknbgnsfxhpcyfwz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5anZpa25iZ25zZnhocGN5Znd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3Njc5MjgsImV4cCI6MjA2OTM0MzkyOH0.bB6tqcQo10EsqbZN5o9C1yVPC5EIKpIbX4R2OtNn7Ac";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});